
# Directories
SRCS_DIR	:= srcs/
RENDERING_DIR := $(SRCS_DIR)rendering/
PARSING_DIR	:= $(SRCS_DIR)parsing/
PARSING_PARSE_DIR	:= $(PARSING_DIR)parse/
PARSING_RAW_MAP_DIR	:= $(PARSING_DIR)raw_map/
CHECKS_TEXTURE_DIR	:= $(SRCS_DIR)parsing/checks_texture/
CHECKS_COLOR_DIR	:= $(SRCS_DIR)parsing/checks_colors/
CHECKS_MAP_BODY	     := $(SRCS_DIR)parsing/checks_map_body/
OBJS_DIR	:= objs/
INCS_DIR	:= includes/
LIBS_DIR	:= libs/

# Compiler and flags
CC			?= cc
CFLAGS		:= -Wall -Wextra -Werror -I./ -I$(INCS_DIR)
LDFLAGS		:= -lm

# Source files (with directories applied)
SRCS		:= $(addsuffix .c, $(addprefix $(SRCS_DIR), main singletons \
					$(addprefix rendering/, render minimap $(addprefix images/, put_pixels images)) \
					$(addprefix events/, handlers key_handlers mouse_handlers) \
					$(addprefix utils/, utils floodfill)) \
					$(addprefix $(PARSING_PARSE_DIR), parse_map parse_error parse_textures parse_colors parse_map_body parsing_utils) \
			 		$(addprefix $(PARSING_RAW_MAP_DIR), store_map_variables store_map_body read_map) \
			 		$(addprefix $(CHECKS_TEXTURE_DIR), check_texture valid_permisions valid_spacing valid_vars \
							valid_duplicates valid_vars_in_map valid_extentions) \
			 		$(addprefix $(CHECKS_COLOR_DIR), checks_colors valid_chars three_values_exists \
							three_values_only valid_range valid_separator trim_spaces) \
					$(addprefix $(CHECKS_MAP_BODY), checks_map_body valid_player \
						valid_map) \
				)

# Object files and dependency files
OBJS 		:= $(SRCS:$(SRCS_DIR)%.c=$(OBJS_DIR)%.o)
DEPS 		:= $(OBJS:.o=.d)

# Rules for compiling source files into object files and generating dependency files
$(OBJS_DIR)%.o: $(SRCS_DIR)%.c
	@mkdir -p $(dir $@)
	@$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

# Include the dependency files generated by the -MMD flag
-include $(OBJS:.o=.d)

BLACK	= \e[1;30m
RED		= \e[1;31m
GREEN	= \e[92m
YELLOW	= \e[1;33m
BLUE	= \e[1;34m
PURPLE	= \e[1;35m
CYAN	= \e[1;36m
WHITE	= \e[1;37m
RESET	= \e[0m
