
CC			?= cc
CFLAGS		:= -Wall -Wextra -Werror

# Directories
SRCS_DIR	:= srcs/
PARSING_DIR	:= $(SRCS_DIR)parsing/
OBJS_DIR	:= objs/
INCS_DIR	:= includes/
LIBS_DIR	:= libs/

CFLAGS		+= -I./ -I$(INCS_DIR)

# Source files (with directories applied)
SRCS		:= $(addsuffix .c, $(addprefix $(SRCS_DIR), main singletons handlers)) \
			$(addsuffix .c, $(addprefix $(PARSING_DIR), parse_map read_raw_map_vars parse_error read_map \
			store_map_body parse_textures parse_colors parse_map_body))

# Object files convertion
OBJS 		:= $(SRCS:$(SRCS_DIR)%.c=$(OBJS_DIR)%.o)
DEPS 		:= $(OBJS:.o=.d)

$(OBJS_DIR)%.o: $(SRCS_DIR)%.c
	@mkdir -p $(dir $@)
	@$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

# Include the dependency files generated by the -MMD flag
-include $(OBJS:.o=.d)
